export const RECEIVED_POSTS = 'RECEIVED_POSTS'
export const RECEIVED_POST = 'RECEIVED_POST'
export const POST_COMMENT_ADDED = 'POST_COMMENT_ADDED'
// export const POST_COMMENT_EDITED = 'POST_COMMENT_EDITED'
// export const POST_COMMENT_DELETED = 'POST_COMMENT_DELETED'

export const POST_COMMENT_REPLY_ADDED = 'POST_COMMENT_REPLY_ADDED'